---
version: "2"

linters:
  enable:
    - dupl
    - errorlint
    - goconst
    - misspell
    - unconvert
    - prealloc
  disable:
    - bodyclose
    - errcheck
    - ineffassign
    - funlen
    - gosec
  settings:
    errorlint:
      errorf: false
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - path: _test.go
        linters:
          - dupl
          - funlen
      - text: "ST1005:"
        linters:
          - staticcheck
